//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employeeinfo()
        {
            this.leaverecord = new HashSet<leaverecord>();
            this.leaverecord1 = new HashSet<leaverecord>();
            this.leavestatistics = new HashSet<leavestatistics>();
        }
    
        public long ID { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public bool Sex { get; set; }
        public string Department { get; set; }
        public int Level { get; set; }
        public System.DateTime HireDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leaverecord> leaverecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leaverecord> leaverecord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leavestatistics> leavestatistics { get; set; }
    }
}
