//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaverecord
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string ReasonForLeave { get; set; }
        public int State { get; set; }
        public string ReasonForReject { get; set; }
        public long LeaderId { get; set; }
    
        public virtual employeeinfo employeeinfo { get; set; }
        public virtual employeeinfo employeeinfo1 { get; set; }
    }
}
