//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSWebSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class leavesystemEntities : DbContext
    {
        public leavesystemEntities()
            : base("name=leavesystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employeeinfo> employeeinfo { get; set; }
        public virtual DbSet<leaverecord> leaverecord { get; set; }
        public virtual DbSet<leavestatistics> leavestatistics { get; set; }
        public virtual DbSet<leavetype> leavetype { get; set; }
    }
}
